### ISSUE TITLE
script error while running json to csv converter 

### ISSUE THREAD

**Issue by chamarts** [YelpArchive/dataset-examples#11]
Hi,

I am trying to run the json to csv converter script but am getting the following error. May I know what am I doing wrong ?  

Traceback (most recent call last):
 File "json_to_csv_converter.py", line 108, in <module>
   parser = optparse.ArgumentParser(
ttributeError: 'module' object has no attribute 'ArgumentParser'

**Comment by sc932** [comment]
What version of python are you using? I tested this with 2.7 and it seemed to be working.

You could also have another optparse installed somewhere: https://stackoverflow.com/questions/6605851/python-newbie-working-with-argparse

Let me know if you are still having issues and I'll dive in deeper.

**Comment by sc932** [comment]
Nevermind, I was testing on 2.6 >.<

I'll fix this. Thanks for catching it @chamarts!

**Comment by chamarts** [comment]
Thanks Scott for quick turn around.

**Comment by sc932** [comment]
Thanks for the heads up @chamarts :)
