### ISSUE TITLE
category_predictor.json missing

### ISSUE THREAD

**Issue by etep** [YelpArchive/dataset-examples#3]
The file category_predictor.json is missing.  It's not clear what is supposed to be in this file, nor how to generate it.

**Comment by amitdatta4990** [comment]
Facing same issue!

**Comment by sc932** [comment]
This is now more explicit in the `README.md`

You generate category_predictor.json from the academic_dataset.json file from yelp.com/academic_dataset.

``` bash
$ python category_predictor/category_predictor.py yelp_academic_dataset.json > category_predictor.json
```
