### ISSUE TITLE
Survivorship

### ISSUE THREAD

**Issue by firmai** [YelpArchive/dataset-examples#38]
Does the data also include restaurants/firms that have closed down, i.e. not just a list of firms that survived up and till publishing ? 

- I will also post the answer on Kaggle, where I have similarly asked the question.

Regards & Thanks

**Comment by tomelm** [comment]
It does not, it only includes current businesses.

**Comment by firmai** [comment]
Thanks Tomer. 

From what I know Yelp does not necessarily partner with institutions/universities to obtain custom sets? We are specifically looking at an added failure/closed set of firms (UoA). 

We are trying a range of prediction tasks using yelp with some added privileged data - employee turnover prediction (with linkedin), revenue prediction (public), churn, failure, success, market cap, corporate governance.  

Regards

**Comment by evan-magnusson** [comment]
Does the "is_open" variable not mean "currently in business?"  I interpreted it to mean the business was still in operation -- not that the data was pulled during it's hours of operation.  In this case, around 10% of the sample are businesses that are no longer in operation.

**Comment by firmai** [comment]
I think you are correct, it would be good to get some formal response on that, this analysis proves your point. 
https://rstudio-pubs-static.s3.amazonaws.com/259585_a28cb43770764a78a0eee04a0fc0702d.html

**Comment by tomelm** [comment]
@evan-magnusson @firmai I checked with the data science team, the `is_open` flag does tell you whether or not the business is still in operation. Apologies for the confusion, please disregard my original answer.

**Comment by evan-magnusson** [comment]
Awesome, thanks for the follow up.
