### ISSUE TITLE
input protocol code error for autopilot

### ISSUE THREAD

**Issue by etep** [YelpArchive/dataset-examples#4]
a patch for autopilot.py -- do you want me to make this a pull request?
- from mrjob.protocol import JSONProtocol
- from mrjob.protocol import JSONValueProtocol
- DEFAULT_INPUT_PROTOCOL = 'json_value'
- INPUT_PROTOCOL = JSONValueProtocol

**Comment by sc932** [comment]
This is fixed in `master` as of #7.

Thanks and sorry for the delay!
