### ISSUE TITLE
question about date availability for business in NYC

### ISSUE THREAD

**Issue by stevenlis** [YelpArchive/dataset-examples#47]
According to the [decritption][1] of the dataset:
>This set includes information about local businesses in 10 metropolitan areas across 2 countries.

I'm using the dataset for a study focusing on health care business in New York City, and I need the information for all health care related business and their reviews in New York City. Right after converting the `.json` file to `.csv` without any further cleaning, I explored the dataset and found that there is only one row in the dataset is  "New York" city and 22 rows are "NY" state. Thus, I wonder if this is a mistake by me or the original dataset is in fact uncomprehensive.

In addtion, I also checked the Fusion API, but there is a number limit for both business and reviews:

>This endpoint returns up to 1000 businesses based on the provided search criteria.

>This endpoint returns up to three review excerpts for a given business ordered by Yelp's default sort order.

Is there any way that I can access all the health care business in NYC and review? 

[1]: https://www.yelp.com/dataset/challenge

**Comment by tiantiandeayi** [comment]
> According to the [decritption](https://www.yelp.com/dataset/challenge) of the dataset:
> 
> > This set includes information about local businesses in 10 metropolitan areas across 2 countries.
> 
> I'm using the dataset for a study focusing on health care business in New York City, and I need the information for all health care related business and their reviews in New York City. Right after converting the `.json` file to `.csv` without any further cleaning, I explored the dataset and found that there is only one row in the dataset is "New York" city and 22 rows are "NY" state. Thus, I wonder if this is a mistake by me or the original dataset is in fact uncomprehensive.
> 
> In addtion, I also checked the Fusion API, but there is a number limit for both business and reviews:
> 
> > This endpoint returns up to 1000 businesses based on the provided search criteria.
> 
> > This endpoint returns up to three review excerpts for a given business ordered by Yelp's default sort order.
> 
> Is there any way that I can access all the health care business in NYC and review?

I also have the same question, have you solved it ?

**Comment by stevenlis** [comment]
@tiantiandeayi I haven't used the API for a long time, so I really can't remember what happened. Sorry.
