### ISSUE TITLE
Problem running category_predictor.py

### ISSUE THREAD

**Issue by jschombe** [YelpArchive/dataset-examples#5]
Hi Everyone,
I am trying to run category_predictor.py but I get the error "string indices must be integers and not str"  I try to run it with the command “category_predictor.py C:\Python27\yelpsample.txt”  s the error in the category_predictor.py code?  Is it in my command line entry?  Is it in the .txt file I submit? The sample pulls strings directly from the yep academic dataset.  Any assistance is appreciated.

**Comment by selik** [comment]
It seems that mrjob is failing to decode the string to json. The script worked after I added

```
if type(data) == str:
    data = json.loads(data)
```

above `if data['type'] == 'review':`.

**Comment by jschombe** [comment]
Could you post a copy of the old code with your new code added?  Thanks for
your work on this!   I am eager to get the code working.

**Comment by sc932** [comment]
This is fixed in `master` as of #7.

Thanks and sorry for the delay!
